version: '3.8'
services:
  hashing:
    build:
      context: .
      dockerfile: hashing/Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      SERVER_ADDRESS: 'hashing:9000'
    ports:
      - "8080:8080"
    depends_on:
      - hashing