version: '3.8'
services:
  hashing:
    build:
      context: .
      dockerfile: hashing/Dockerfile
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      HASHING_ADDRESS: "hashing:9000"
    networks:
      - "hashservice"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      HASHING_ADDRESS: "hashing:9000"
      GATEWAY_PORT: ":8080"
    ports:
      - "8080:8080"
    networks:
      - "hashservice"
    depends_on:
      - hashing

networks:
  hashservice:
    name: "hashservice"